### ISSUE TITLE
New designs for the editor

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#7729] opened 2023-03-11 08:35 UTC
use figma, then implement with new components & storybook isolation

**Comment by dikshashukla455** [comment] 2023-03-11 18:10
hi, can i work on this issue?

**Comment by SYBIOTE** [comment] 2023-08-28 21:36
duplicate of https://github.com/EtherealEngine/etherealengine/issues/7950

**Closed** 2023-08-28 22:45 UTC
Labels: story - 8
