### ISSUE TITLE
[Bug]: Replacing Model URL Causes Runaway Client Input Raycast Errors

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9170] opened 2023-10-30 16:10 UTC
### Operating System

Any

### What happened?

When the model URL is changed in studio, after the new model loads, every frame triggers multiple errors in the Client Input System:

https://github.com/EtherealEngine/etherealengine/assets/94419856/43ab7ead-8376-4a5e-b90a-7f5b1666cf66

![brave_xGIUwAQQNk](https://github.com/EtherealEngine/etherealengine/assets/94419856/c560f2d7-b8bd-4604-b60e-9a157139ff0d)

### Steps to reproduce

```shell
1. Open any scene with a Model Component present
2. Replace the URL in the Model Component with some other model
3. After loading, observe log to see thousands of raycast errors
```

### Relevant log output

```shell
SystemFunctions.tsx:100 TypeError: Cannot read properties of undefined (reading 'getX')
    at _Vector3.fromBufferAttribute (three.module.js:4579:22)
    at checkBufferGeometryIntersection (ThreeRayIntersectUtilities.js:46:6)
    at intersectTri (ThreeRayIntersectUtilities.js:126:23)
    at intersectTris (iterationUtils.generated.js:15:3)
    at _raycast (raycast.generated.js:32:3)
    at _raycast (raycast.generated.js:47:4)
    at _raycast (raycast.generated.js:47:4)
    at _raycast (raycast.generated.js:47:4)
    at _raycast (raycast.generated.js:40:4)
    at _raycast (raycast.generated.js:40:4)
```

**Comment by SYBIOTE** [comment] 2023-12-12 00:19
cannot reproduce, is this still an issue?

**Comment by SYBIOTE** [comment] 2023-12-20 09:30
closing this

**Closed by SYBIOTE** 2023-12-20 09:30 UTC
Labels: bug
