### ISSUE TITLE
[Bug]: Hierarchy Panel is Blank When Switching Back from Material Library

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#8704] opened 2023-09-08 21:05 UTC
In the studio, after selecting a different tab of the panel holding the Hierarchy, when switching back to hierarchy the panel is blank
![image](https://github.com/EtherealEngine/etherealengine/assets/94419856/346ab5db-7ad8-41ef-b56e-18535d74d898)

**Comment by SYBIOTE** [comment] 2023-09-13 20:15
cannot reproduce in local or dev

**Comment by SYBIOTE** [comment] 2023-09-15 21:56
i think its happens when there is no entity selected / under focus 
im not sure how that triggers when switching back from the material panel though

**Comment by SYBIOTE** [comment] 2023-10-16 04:23
cannot replicate, closing

**Closed** 2023-10-16 04:24 UTC
Labels: bug
