### ISSUE TITLE
[Bug]: Chat is very slow, Messages disappear, and don't label who sent message

### ISSUE THREAD

**Issue by DanielBelmes** [EtherealEngine/etherealengine#9258] opened 2023-11-10 23:09 UTC
### Operating System

Ubuntu

### Browser (if applicable)

Chromium

### Website

dev.etherealengine.com

### What happened?

When using chat and sending a message the message takes quite awhile to appear. Sometimes the message disappears.

### Steps to reproduce

```shell
Open chat on dev or app. Then type message and send.

Takes about 10 seconds for message to appear in chat.
```

**Comment by heysokam** [comment] 2024-05-01 02:11
~~Chat is indeed slow, and it sends messages in the wrong order sometimes.~~
~~I cannot reproduce the `10 messages limit` ticket, but this one is definitely active~~
_edit: nvm, I misunderstood the reason for closing it. the other ticket at #9051 should indeed close this :writing_hand:_

**Closed** 2024-05-01 02:27 UTC
Labels: bug
