### ISSUE TITLE
Dual Quaternions for Avatar Pose

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#4300] opened 2021-11-29 00:21 UTC

**Comment by speigg** [comment] 2023-08-23 23:49
Effectively, a duplicate of [Split TransformComponent into PoseComponent and ScaleComponent](https://github.com/EtherealEngine/etherealengine/issues/7478) after https://github.com/EtherealEngine/etherealengine/pull/8137

**Closed by speigg** 2023-08-23 23:49 UTC
Labels: story - 4
